[mgr]
show_hidden = true
[opener]
# open = [
# 	{ run = 'xdg-open "$@"', desc = "Open" },
# ]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
# [open]
# prepend_rules = [
# 	{ mime = "text/*", use = "edit" },
# 	{ mime = "*.lua", use = "edit" },
# 	{ mime = "*.tex", use = "edit" },
# 	{ mime = "*.lua", use = "edit" },
# 	{ mime = "*.py", use = "edit" },
# 	{ mime = "*.bib", use = "edit" },
# 	{ name = "*.rnote", use = "open" },
# 	{ name = "*", use = "open" },
# ]
