#!/bin/sh
#if [ -d ~/.tmux/plugins/tpm ];
#then
#    echo "Tmux TPM Installed"
#else
#    echo "Installing Tmux TPM"
#    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
#fi
stow home
