#!/bin/bash

uselastwp()
{
    feh --bg-scale "~/Pictures/"${$(ls ~/Pictures/wallpaper*.png)[-1]}
}
usewp()
{
    feh --bg-scale "~/Pictures/"${$(ls ~/Pictures/wallpaper*.png)[1]}
}
addwp () # add wallpaper from buffer : /tmp/latest-screenshot.png
{
    size=${#$(ls ~/Pictures/wallpaper*.png)[@]}
    newnumber=$[size+1]
    newname=$(echo ~/Pictures/wallpaper$newnumber".png")
    
    if mv /tmp/latest-screenshot.png $newname
    then
	feh --bg-scale $newname
	echo "Success"
    else
	echo "Failure"
    fi
}
