[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"


[[manager.prepend_keymap]]
on   = [ "<Right>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"


# [[manager.prepend_keymap]]
# on   = [ "l" ]
# run  = "plugin --sync zoxide-logger"
# desc = "Log to zoxide"
#
#
# [[manager.prepend_keymap]]
# on   = [ "<Right>" ]
# run  = "plugin --sync zoxide-logger"
# desc = "Log to zoxide"
