#!/usr/bin/bash
sleep 0.1
# ydotool click --repeat 2 0xC0
if [ $XDG_SESSION_TYPE = wayland ]
then
	url-launcher "https://dictionary.cambridge.org/dictionary/english/$(wl-paste --primary)"
else
	url-launcher "https://dictionary.cambridge.org/dictionary/english/$(xsel -o)"
fi
