#!/usr/bin/python3
import time
import os
import fileinput
import subprocess
from anki_connect import invoke

for line in fileinput.input():
    sentences = subprocess.run(
        ["yourdictionary", "-n", "0", "-t", "sentence", line], capture_output=True, text=True)
    sentences = sentences.stdout
    for sentence in sentences.splitlines():
        sentence_num_words = len(sentence.split())
        if sentence_num_words > 20:
            continue
        ps = subprocess.Popen(
            ("trans", "-show-original=n","en:pt", sentence), stdout=subprocess.PIPE)
        ps.wait()
        definition = subprocess.check_output(
            ("sed", r"s/.\[[0-9]\{1,\}m//g"), stdin=ps.stdout)
        definition = definition.decode('utf-8')
        definition=definition.replace('\n',"<br>")
        print(sentence, '|', definition, end='')
        invoke('addNote', note={
            "deckName": "M::English Sentences Audio::2",
               "modelName": "Basic translate speak",
               "fields": {
                   "Front": sentence,
                   "Back": definition
               },
               "options":{
                   "allowDuplicate":True}
               })
        time.sleep(1)
    time.sleep(0.2)
