#!/usr/bin/zsh

urlencode() {
    setopt localoptions extendedglob
    input=( ${(s::)1} )
    print ${(j::)input/(#b)([^A-Za-z0-9_.\!~*\'\(\)-])/%${(l:2::0:)$(([##16]#match))}}
}

if [ $XDG_SESSION_TYPE = wayland ]
then
	temp=$(wl-paste --primary)
else
	temp=$(xsel -o)
fi
# echo $temp
url-launcher 'https://translate.google.com/?sl=auto&tl=pt&text='"$temp"'&op=translate'
