#!/usr/bin/bash

if [ $XDG_SESSION_TYPE = wayland ]
then
	temp=$(wl-paste --primary)
else
	temp=$(xsel -o)
fi
temp=$(echo $temp | tr '\n' ' ')
request='{
    "action": "addNote",
    "params": {
        "note": {
            "deckName": "M::Languages::English::English Words",
            "modelName": "Basic",
            "fields": {
                "Front": "'"$temp"'",
                "Back": ""
            }
        }
    }
}'
curl localhost:8765 -X POST -d "$request"
