#!/usr/bin/env python3
import argparse
from typing import Any
import urllib.request
from bs4 import BeautifulSoup
from bs4.element import ResultSet

# soup = BeautifulSoup("<html>a web page</html>", 'html.parser')
parser= argparse.ArgumentParser()
parser.add_argument('-n',default=None,type=int)
parser.add_argument('-t',default="sentence",type=str,choices=["sentence","meaning","synonym"])
parser.add_argument('w',default=None,type=str)
args=parser.parse_args()
if args.w == None or args.w == "":
    raise ValueError("Must pass a word to search")

str_target=''
if args.t == 'meaning':
    str_target=''
elif args.t == "sentence":
    str_target= "sentence."
elif args.t == 'synonym':
    str_target='thesaurus.'
else:
    raise ValueError("There is no "+args.t+" type available")

target_url="https://"+str_target+"yourdictionary.com/"+args.w
# print(target_url)
result =urllib.request.urlopen(target_url)
contents =  result.read()
soup = BeautifulSoup(contents, 'html.parser')

a:ResultSet[Any]
if args.t == 'sentence':
    a=soup.find_all(class_='sentence-item__text',limit=args.n)
elif args.t == 'meaning':
    a=soup.find_all(class_='compiled-defintion',limit=args.n)
else:
    a=soup.find_all(class_='sentence-item__text',limit=args.n)
    raise ValueError("There is no "+args.t+" type available")

for i in a:
    print(i.get_text())
